const BOSSES=["스우","데미안","루시드","윌","더스크","진힐라","듄켈","세렌","칼로스","카링","림보","대적자","흉성","벨로나","검은 마법사"];
const MONTHLY=new Set(["검은 마법사"]),SOLO=new Set(["데미안","루시드","윌","더스크","진힐라","듄켈"]),LIMIT=12,DIFFS=["","x","이지","노말","하드","카오스","익스트림"];
const INITIAL={players:["오똑","쇼똑","오뿡","옥수수목금","파똑"],cells:{
"스우":[["익스트림","1인"],["익스트림","2인\n키네달별"],["익스트림","2인\n웃토"],["익스트림","2인\n콩국수목금"],["익스트림","2인\n달하늘의치킨"]],
"데미안":[["x","x"],["x","x"],["x","x"],["",""],["",""]],
"루시드":[["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"]],
"윌":[["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"]],
"더스크":[["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"]],
"진힐라":[["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"],["하드","1인"]],
"듄켈":[["x","x"],["x","x"],["하드","1인"],["",""],["",""]],
"세렌":[["익스트림","3인\n츠죠, 웃토"],["익스트림","3인\n피콕, 꿈품은"],["하드","1인"],["",""],["",""]],
"칼로스":[["카오스","2인\n츠죠"],["노말","1인"],["노말","1인"],["",""],["",""]],
"카링":[["하드","4인\n피콕, 츠죠, 꿈품은"],["노말","3인\n웃토, 츠죡"],["이지","1인"],["",""],["",""]],
"림보":[["노말","2인\n츠죠"],["노말","3인\n꿈품은, 렌별달"],["x","x"],["",""],["",""]],
"대적자":[["하드","3인\n츠죠, 꿈품은"],["노말","1인"],["노말","1인"],["",""],["",""]],
"흉성":[["노말","1인"],["노말","2인\n달하늘의치킨"],["노말","2인\n미정"],["",""],["",""]],
"벨로나":[["노말","2인\n츠죡"],["이지","1인"],["이지","1인"],["",""],["",""]],
"검은 마법사":[["익스트림","4인\n웃토, 꿈쉐릴, 키네달별"],["익스트림","3인\n츠죠, 달하늘의치킨"],["익스트림","3인\n피콕, 츠죠"],["",""],["",""]]}};
const KEY="boss-board-v4-owners";
function cp(v){return JSON.parse(JSON.stringify(v))}
function uid(){return"owner-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7)}
function parseParty(v){var t=String(v||"").trim();if(!t||t.toLowerCase()==="x")return{count:0,names:[]};var a=t.split(/\n+/).map(function(x){return x.trim()}).filter(Boolean),m=(a[0]||"").match(/(\d+)\s*인/),c=m?Math.max(1,Math.min(6,+m[1])):1,n=a.slice(1).join(",").split(",").map(function(x){return x.trim()}).filter(Boolean);return{count:c,names:n.slice(0,Math.max(0,c-1))}}
function normBoard(s){if(!s||!Array.isArray(s.players)||!s.cells)s=cp(INITIAL);BOSSES.forEach(function(b){if(!Array.isArray(s.cells[b]))s.cells[b]=[];while(s.cells[b].length<s.players.length)s.cells[b].push({difficulty:"",count:0,names:[]});s.cells[b]=s.cells[b].slice(0,s.players.length).map(function(v){if(Array.isArray(v)){var p=parseParty(v[1]);return{difficulty:v[0]||"",count:SOLO.has(b)&&v[0]&&v[0]!=="x"?1:p.count,names:SOLO.has(b)?[]:p.names}}var d=(v&&v.difficulty)||"",c=Math.max(0,Math.min(6,Number(v&&v.count)||0));if(SOLO.has(b))c=d&&d!=="x"?1:0;return{difficulty:d,count:c,names:SOLO.has(b)?[]:(Array.isArray(v&&v.names)?v.names.slice(0,Math.max(0,c-1)):[])}})});return s}
function blank(n){var c={};BOSSES.forEach(function(b){c[b]=[{difficulty:"",count:0,names:[]}]});return{players:[n||"새 캐릭터"],cells:c}}
function normApp(a){if(!a||!Array.isArray(a.owners)||!a.owners.length)a={owners:[{id:"owner-ottok",name:"오똑",board:normBoard(cp(INITIAL))}],activeOwnerId:"owner-ottok"};a.owners=a.owners.map(function(o,i){return{id:o.id||uid(),name:String(o.name||("주인 "+(i+1))),board:normBoard(o.board)}});if(!a.owners.some(function(o){return o.id===a.activeOwnerId}))a.activeOwnerId=a.owners[0].id;return a}
function load(){try{if(location.hash.indexOf("#data=")===0){var raw=decodeURIComponent(escape(atob(location.hash.slice(6)))),p=JSON.parse(raw),x=p.owners?normApp(p):normApp({owners:[{id:"owner-ottok",name:"오똑",board:normBoard(p)}],activeOwnerId:"owner-ottok"});localStorage.setItem(KEY,JSON.stringify(x));history.replaceState(null,"",location.pathname+location.search);return x}var s=localStorage.getItem(KEY);if(s)return normApp(JSON.parse(s))}catch(e){}return normApp(null)}
var APP=load(),timer;
function owner(){return APP.owners.find(function(o){return o.id===APP.activeOwnerId})||APP.owners[0]}
function state(){return owner().board}
function save(){clearTimeout(timer);document.getElementById("saveText").textContent="저장 중…";timer=setTimeout(function(){localStorage.setItem(KEY,JSON.stringify(APP));document.getElementById("saveText").textContent="이 브라우저에 자동 저장됨"},150)}
function esc(s){return String(s).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
function planned(c){return!!c&&c.difficulty!==""&&c.difficulty!=="x"}
function weekly(pi,except){var st=state();return BOSSES.reduce(function(n,b){return b===except||MONTHLY.has(b)?n:n+(planned(st.cells[b]&&st.cells[b][pi])?1:0)},0)}
function monthly(pi){var st=state();return BOSSES.reduce(function(n,b){return n+(MONTHLY.has(b)&&planned(st.cells[b]&&st.cells[b][pi])?1:0)},0)}
function toast(m){var e=document.getElementById("toast");e.textContent=m;e.classList.add("show");setTimeout(function(){e.classList.remove("show")},1800)}
function members(c,bi,pi){if(!c.count)return'<div class="solo">인원수 선택</div>';if(c.count===1)return'<div class="solo">본인 단독</div>';var h='<div class="member-list">';for(var i=0;i<c.count-1;i++)h+='<input class="member" data-b="'+bi+'" data-p="'+pi+'" data-m="'+i+'" value="'+esc(c.names[i]||"")+'" placeholder="파티원 '+(i+1)+' 이름">';return h+"</div>"}
function renderOwners(){var el=document.getElementById("ownerTabs");el.innerHTML=APP.owners.map(function(o){return'<button class="owner-tab '+(o.id===APP.activeOwnerId?"active":"")+'" data-owner="'+esc(o.id)+'">'+esc(o.name)+"</button>"}).join("");el.querySelectorAll("[data-owner]").forEach(function(b){b.onclick=function(){APP.activeOwnerId=b.dataset.owner;save();render()}});document.getElementById("boardTitle").textContent=owner().name+"의 보스 현황"}
function render(){renderOwners();var st=state(),h='<thead><tr><th class="boss-head">BOSS</th>';st.players.forEach(function(p,i){var w=weekly(i),m=monthly(i);h+='<th class="player-head"><div class="player-row"><input class="player-input" data-player="'+i+'" value="'+esc(p)+'"><button class="remove-player" data-remove="'+i+'">×</button></div><div class="sub"><span class="'+(w>=LIMIT?"full":"")+'">주간 '+w+"/"+LIMIT+"</span> · 월간 "+m+"/1</div></th>"});h+="</tr></thead><tbody>";BOSSES.forEach(function(b,bi){var mon=MONTHLY.has(b);h+='<tr class="'+(mon?"monthly-row":"")+'"><td class="boss"><div class="boss-name"><span>'+b+'</span><span class="badge '+(mon?"monthly":"")+'">'+(mon?"월간":"주간")+"</span></div></td>";st.players.forEach(function(_,pi){var c=st.cells[b][pi]||{difficulty:"",count:0,names:[]},opts=DIFFS.map(function(x){return'<option value="'+esc(x)+'" '+(x===c.difficulty?"selected":"")+'>'+(x||"—")+"</option>"}).join("");var party;if(SOLO.has(b))party='<div class="solo">'+(planned(c)?"1인 고정":"난이도 선택 시 1인")+"</div>";else{var counts=[1,2,3,4,5,6].map(function(n){return'<label class="count"><input type="radio" name="c-'+bi+"-"+pi+'" data-count="'+n+'" data-b="'+bi+'" data-p="'+pi+'" '+(c.count===n?"checked":"")+'><span>'+n+"인</span></label>"}).join("");party='<div class="counts">'+counts+"</div>"+members(c,bi,pi)}h+='<td class="slot"><div class="slot-grid"><select class="difficulty" data-b="'+bi+'" data-p="'+pi+'" data-v="'+esc(c.difficulty)+'">'+opts+'</select><div class="party">'+party+"</div></div></td>"});h+="</tr>"});h+="</tbody>";document.getElementById("board").innerHTML=h;bind()}
function bind(){var st=state();document.querySelectorAll(".player-input").forEach(function(e){e.oninput=function(){st.players[+e.dataset.player]=e.value;save()}});document.querySelectorAll(".difficulty").forEach(function(e){e.onchange=function(){var b=BOSSES[+e.dataset.b],pi=+e.dataset.p,c=st.cells[b][pi],n=e.value;if(!MONTHLY.has(b)&&n&&n!=="x"&&!planned(c)&&weekly(pi,b)>=LIMIT){toast("주간 보스는 최대 "+LIMIT+"개까지만 선택할 수 있어요.");render();return}c.difficulty=n;if(!n||n==="x"){c.count=0;c.names=[]}else if(SOLO.has(b)){c.count=1;c.names=[]}save();render()}});document.querySelectorAll("[data-count]").forEach(function(e){e.onchange=function(){if(!e.checked)return;var b=BOSSES[+e.dataset.b],pi=+e.dataset.p,c=st.cells[b][pi],n=+e.dataset.count;if(SOLO.has(b))return;c.count=n;c.names=(c.names||[]).slice(0,Math.max(0,n-1));while(c.names.length<n-1)c.names.push("");save();render()}});document.querySelectorAll(".member").forEach(function(e){e.oninput=function(){var b=BOSSES[+e.dataset.b];st.cells[b][+e.dataset.p].names[+e.dataset.m]=e.value;save()}});document.querySelectorAll("[data-remove]").forEach(function(e){e.onclick=function(){var i=+e.dataset.remove;if(st.players.length<=1){toast("캐릭터는 1명 이상 있어야 해요.");return}if(!confirm("“"+(st.players[i]||"캐릭터")+"” 열을 삭제할까요?"))return;st.players.splice(i,1);BOSSES.forEach(function(b){st.cells[b].splice(i,1)});save();render()}})}
document.getElementById("addOwner").onclick=function(){var n=(prompt("새 보스판의 주인 이름을 입력해 주세요. 예: 츠죠")||"").trim();if(!n)return;var o={id:uid(),name:n,board:blank(n)};APP.owners.push(o);APP.activeOwnerId=o.id;save();render();toast(n+" 보스판을 만들었어요.")};
document.getElementById("renameOwner").onclick=function(){var o=owner(),n=(prompt("주인 이름을 수정해 주세요.",o.name)||"").trim();if(!n)return;o.name=n;save();render()};
document.getElementById("removeOwner").onclick=function(){if(APP.owners.length<=1){toast("보스판은 1개 이상 있어야 해요.");return}var o=owner();if(!confirm("“"+o.name+"” 보스판 전체를 삭제할까요?"))return;APP.owners=APP.owners.filter(function(x){return x.id!==o.id});APP.activeOwnerId=APP.owners[0].id;save();render()};
document.getElementById("addPlayer").onclick=function(){var st=state();st.players.push("새 닉네임");BOSSES.forEach(function(b){st.cells[b].push({difficulty:"",count:0,names:[]})});save();render();setTimeout(function(){var a=document.querySelectorAll(".player-input"),e=a[a.length-1];e.focus();e.select()},0)};
document.getElementById("resetBtn").onclick=function(){if(!confirm("모든 주인과 보스판을 지우고 오똑 원본 상태로 되돌릴까요?"))return;APP=normApp(null);localStorage.setItem(KEY,JSON.stringify(APP));render();toast("오똑 원본 상태로 초기화했어요.")};
document.getElementById("shareBtn").onclick=async function(){try{var encoded=btoa(unescape(encodeURIComponent(JSON.stringify(APP)))),url=location.href.split("#")[0]+"#data="+encoded;await navigator.clipboard.writeText(url);toast("모든 보스판이 담긴 공유 링크를 복사했어요.")}catch(e){toast("브라우저에서 링크 복사가 제한됐어요.")}};
render();